config/routes.rb
Rails.application.routes.draw do
  resources :questions, only: [:index, :new, :show, :create, :edit, :update, :destroy] do
    resources :answers, only: [:create]
  end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :questions

  validates :description, presence: {:message => "You must provide a description"}

end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers, dependent: :destroy

  validates :title, presence:  {:message => "You must provide a title"}
  validates :description, presence: {:message => "You must provide a description"}

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  # def new
  #   @answer = Answer.new
  # end

  # def create
  #   @answer = Answer.new(answer_params)
  #   if @answer.save
  #   else
  #     render :new
  #   end
  # end

  def create
  @answer = Answer.new(answer_params)
  @answer.question_id = params[:question_id]
  @question=Question.find(params[:question_id])
    if @answer.save
      redirect_to @question
    else
      render "questions/show"
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:description, :question_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])
    # @answers = Answer.all
    # not neccesary because relation stated in model
    @answer = Answer.new
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      redirect_to question_path(@question)
    else
      render :new
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    if @question.update(question_params)
      redirect_to @question
    else
      render 'edit'
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    redirect_to questions_path
  end

  private

  def question_params
    params.require(:question).permit(:title, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RescueMission</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/questions/edit.html.erb
<h1>Edit a Question</h1>

<%= form_for @question, url: question_path(@question), method: :patch do |f| %>
  <% if @question.errors.any? %>
    <p> There were errors with your submission:</p>
    <ul>
      <% @question.errors.full_messages.each do |msg|%>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <%= f.submit %>
<%end%>
<%= link_to 'Destroy', question_path(@question),
                    method: :delete, data: { confirm: 'Are you sure?' } %>

<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<h1>Questions</h1>

<a href="/questions/new">Post a Question</a>
<br/>
<ul>
  <% @questions.each do |question| %>
    <li><%= link_to question.title, question_path(question) %></li>
  <% end %>
</ul>

app/views/questions/new.html.erb
<h1>Post a Question</h1>

<%= form_for @question do |f| %>
  <% if @question.errors.any? %>
    <p> There were errors with your submission:</p>
    <ul>
      <% @question.errors.full_messages.each do |msg|%>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <%= f.submit %>
<%end%>

app/views/questions/show.html.erb
<a href="/questions">See All Questions</a>

<h2>Answer this question!</h2>

<%= link_to 'Edit', edit_question_path(@question) %>
<%= link_to 'Destroy', question_path(@question),
                    method: :delete, data: { confirm: 'Are you sure?' } %>


<p>Title: <%= @question.title %></p>
<p>Description: <%= @question.description %></p>
<br/>

<%= form_for [@question, @answer] do |f| %>
  <% if @answer.errors.any? %>
    <p> There were errors with your submission:</p>
    <ul>
      <% @answer.errors.full_messages.each do |msg|%>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <div>
    <%= f.label :answer %>
    <%= f.text_area :description %>
  </div>
  <%= f.submit %>
<%end%>

<ul>
<% @question.answers.each do |answer| %>
  <li><%= answer.description %></li>
  <% end %>
</ul>